// SOUNDS is the array of all recognized sounds and their features
export const SOUNDS = [
  {
    symbol: 't',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'd',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 's',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: true,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'z',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: true,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɬ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: true,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: true,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɮ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: true,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'θ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ð',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʃ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʒ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'c',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɟ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ç',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʝ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'p',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'b',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'f',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: true,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'v',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: true,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɸ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'β',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'k',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'g',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'x',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɣ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'q',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɢ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'χ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʁ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ħ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: true,
    atr: false,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  //CHANGED TO +VOICE
  {
    symbol: 'ʕ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'h',
    consonantal: false,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: true,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɦ',
    consonantal: false,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: true,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʔ',
    consonantal: false,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: true,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  //TODO: decide continuancy
  {
    symbol: 't͡ʃ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: true,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 'd͡ʒ',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: true,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: true,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 't͡s',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: true,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 'd͡z',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: true,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 'k͡x',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 'p͡f',
    consonantal: true,
    sonorant: false,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: false,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: true,
    lateral: false,
    delayedrelease: true,
    nasal: false
  },
  {
    symbol: 'm',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'n',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'ŋ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'ɳ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: false,
    distributed: false,
    dorsal: true,
    high: false,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'ɲ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'ɴ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: false,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: true
  },
  {
    symbol: 'l',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: true,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʎ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: true,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'r',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɹ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: true,
    anterior: true,
    distributed: false,
    dorsal: false,
    high: null,
    low: null,
    back: null,
    tense: null,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʀ',
    consonantal: true,
    sonorant: true,
    syllabic: false,
    labial: false,
    round: null,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'j',
    consonantal: false,
    sonorant: true,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'w',
    consonantal: false,
    sonorant: true,
    syllabic: false,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɥ',
    consonantal: false,
    sonorant: true,
    syllabic: false,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɰ',
    consonantal: false,
    sonorant: true,
    syllabic: false,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: false,
    atr: null,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'i',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɪ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'u',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʊ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'e',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: false,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɛ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: false,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'o',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɔ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'a',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: true,
    back: false,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'æ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: true,
    back: false,
    tense: true,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'y',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ʏ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: false,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ø',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: false,
    tense: true,
    pharyngeal: true,
    atr: true,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  //Sus not rounded
  {
    symbol: 'œ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: false,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: false,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ə',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: false,
    low: false,
    back: true,
    tense: false,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  },
  {
    symbol: 'ɯ',
    consonantal: false,
    sonorant: true,
    syllabic: true,
    labial: true,
    round: true,
    coronal: false,
    anterior: null,
    distributed: null,
    dorsal: true,
    high: true,
    low: false,
    back: true,
    tense: true,
    pharyngeal: true,
    atr: false,
    voice: true,
    spreadglottis: false,
    constrictedglottis: false,
    continuant: true,
    strident: false,
    lateral: false,
    delayedrelease: false,
    nasal: false
  }
]

export const FEATURES = [
  '+consonantal',
  '-consonantal',
  '+sonorant',
  '-sonorant',
  '+syllabic',
  '-syllabic',
  '+labial',
  '-labial',
  '+round',
  '-round',
  '+coronal',
  '-coronal',
  '+anterior',
  '-anterior',
  '+distributed',
  '-distributed',
  '+dorsal',
  '-dorsal',
  '+high',
  '-high',
  '+low',
  '-low',
  '+back',
  '-back',
  '+tense',
  '-tense',
  '+pharyngeal',
  '-pharyngeal',
  '+atr',
  '-atr',
  '+voice',
  '-voice',
  '+spreadglottis',
  '-spreadglottis',
  '+constrictedglottis',
  '-constrictedglottis',
  '+continuant',
  '-continuant',
  '+strident',
  '-strident',
  '+lateral',
  '-lateral',
  '+delayedrelease',
  '-delayedrelease',
  '+nasal',
  '-nasal',
  ]


// getSoundsWithProperty(property) returns all sounds that match property
const getSoundsWithProperty = (property) => {
  let propName = property[0];
  let propValue = property[1];
  let matches = [];
  let sound;

  for (sound of SOUNDS) {
    if (sound[propName] === propValue) {
      matches.push(sound.symbol);
    }
  }
  return matches;
}

// checkInv(matches, inventory) is all the union of matches and inventory
const checkInv = (matches, inventory) => {
  let i = 0;
  while (i < matches.length) {
    if (inventory.indexOf(matches[i]) === -1) {
      matches.splice(i, 1);
    } else {
      i++;
    }
  }
  return matches;
}

// getSoundsWithProperties(properties, inventory) is an array of all sounds in inventory
// that match properties
// properties is of form [[featureName, boolean]...]
export const getSoundsWithProperties = (properties, inventory) => {
  let i;
  let matches = [];
  for (i = 0; i < properties.length; i++) {
    const property = properties[i];
    const tempMatches = getSoundsWithProperty(property);
    if (i === 0) {
      matches = tempMatches;
    }
    else {
      matches = matches.filter(s => tempMatches.includes(s));
    }
  }
  return checkInv(matches, inventory);
}